// src/components/AddNewPlaceholder/AddNewPlaceholder.tsx
import AddIcon from './add-icon.png'
import styles from './AddNewPlaceholder.css'

interface Props {
  onClickNewPlaceholder: () => void
}

export const AddNewPlaceholder = ({ onClickNewPlaceholder }: Props) => {
  return (
    <section className={styles.section} onClick={onClickNewPlaceholder}>
      <img className={styles.icon} src={AddIcon} alt='add card icon' />
    </section>
  )
}

// src/lib/AddNewPlaceholder.svelte
<script lang="ts">
  import AddIcon from './add-icon.png'

  function handleClick() {
    console.log(777, 'click')
  }
</script>

<section on:click={handleClick}>
  <img src={AddIcon} alt="add card icon" />
</section>

<style>
  section {
    background-color: rgba(255, 255, 255, 0.09);
    padding: 16px;
    border-radius: 10px;
    display: flex;
    justify-content: center;
    cursor: pointer;
  }

  section:hover {
    border: 1px solid #ffffffde;
    box-sizing: border-box;
  }

  img {
    width: 50px;
  }
</style>
